### ISSUE TITLE
doctype-first error

### ISSUE THREAD

**Issue by jose4125** [htmlhint/HTMLHint#566]
**Describe the bug**
I'm using htmlhint as a script in my package.json
`"lint:html": "htmlhint --config .htmlhintrc ./src/**/*.html"`

my .htmlhintrc
```
{
  "doctype-first": false,
  "doctype-html5": false,
  "head-script-disabled": false
  "style-disabled": false,
  "title-require": false,
  "attr-lowercase": true,
  "attr-no-duplication": true,
  "attr-no-unnecessary-whitespace": true,
  "attr-unsafe-chars": true,
  "attr-value-double-quotes": true,
  "attr-value-not-empty": false,
  "alt-require": true,
  "tagname-lowercase": false,
  "input-requires-label": true,
  "tags-check": true.
  "tag-pair": true,
  "tag-self-close": true,
  "tagname-lowercase": true,
  "empty-tag-not-self-closed": true,
  "src-not-empty": true,
  "href-abs-or-rel": false,
  "id-class-ad-disabled": true,
  "id-class-value": true,
  "id-unique": true,
  "inline-script-disabled": true,
  "inline-style-disabled": true,
  "space-tab-mixed-disabled": "space",
  "spec-char-escape": false,
}
```
I'm creating components per html like
`<div class="my-component">...</div>`

and I'm getting an error
```
 L1 |<div class="my-component"></div>
          ^ Doctype must be declared first. (doctype-first)

```
How could I disable this rule?, right now I have disabled this rule in my config `"doctype-first": false,`, but It is not desabled

**Comment by chriscorchado125** [comment]
Try the code below in your package.json:
  "scripts": {
      "lint": "npx htmlhint ./src/**/*.html"
  }

Make sure the htmlhintrc is in the root folder and then from the root folder run the following command from the command line:  npm run lint

**Comment by eoinkelly** [comment]
Thare are some formatting errors in your JSON config file which are causing it to be silently ignored (errors annotated with comments below):

```jsonc
{
  "doctype-first": false,
  "doctype-html5": false,
  "head-script-disabled": false // missing comma
  "style-disabled": false,
  "title-require": false,
  "attr-lowercase": true,
  "attr-no-duplication": true,
  "attr-no-unnecessary-whitespace": true,
  "attr-unsafe-chars": true,
  "attr-value-double-quotes": true,
  "attr-value-not-empty": false,
  "alt-require": true,
  "tagname-lowercase": false,
  "input-requires-label": true,
  "tags-check": true. // period instead of comma
  "tag-pair": true,
  "tag-self-close": true,
  "tagname-lowercase": true,
  "empty-tag-not-self-closed": true,
  "src-not-empty": true,
  "href-abs-or-rel": false,
  "id-class-ad-disabled": true,
  "id-class-value": true,
  "id-unique": true,
  "inline-script-disabled": true,
  "inline-style-disabled": true,
  "space-tab-mixed-disabled": "space",
  "spec-char-escape": false, // trailing comma
}
```

**Comment by snowinmars** [comment]
Still have same issue:

.htmlhintrc.json
```
{
  "doctype-first": false
}
```

```
$ ls . | grep .htmlhintrc.json
.htmlhintrc.json

$
npx htmlhint --config .htmlhintrc.json "**/*.html"
      L1 |﻿<div>
            ^ Doctype must be declared first. (doctype-first)
```

Fixed with setting encoding from `UTF-8 with BOM` to `UTF-8`.

It's a shame that if a explicitly passed config is broken, the code uses defaults as if it was intended.

**Comment by Shelagh-Lewins** [comment]
@snowinmars can you explain your solution please? I don't see how your config is broken - and what encoding did you change? I tried file > save with encoding > UTF8 on both my .html and .htmlhintrc files (Sublime Text 3) and I still have the same problem, that the doctype-first error is showing.

.htmlhintrc

```
{
  "doctype-first": false
}
```

**Comment by Shelagh-Lewins** [comment]
After more investigation I found that for some reason the .htmlhintrc file in my project root wasn't being loaded, and manually specified it in my Sublime Linter settings:

    "linters": {
        "htmlhint": {
            "args": ["--config", ".htmlhintrc"]
        },
    },
